# This is a basic workflow to help you get started with Actions

name: matrix test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [id, vn, us]
        include:
          - aws_region: ap-southeast-1
            region: id
          - aws_region: ap-southeast-2
            region: vn
          - aws_region: us-east-1
            region: us

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
