name: Pushed to develop

on:
  push:
    branches:
      - develop

jobs:
  version-bump:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version Bump
        uses:  phips28/gh-action-bump-version@master
        with:
          tag-prefix: v
          major-wording: release
          minor-wording: feature,feat,add,new

  deploy:
    needs: version-bump
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to develop"
