name: Pushed to develop

on:
  push:
    branches:
      - develop

jobs:
  check-pr:
    runs-on: ubuntu-22.04
    steps:
      - name: Check event
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"