name: Pushed to main

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml

  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to develop"
        