name: Pushed to main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Printing Environment Variables:"
          echo "-----------------------------------------"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED: $GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "RUNNER_ARCH: $RUNNER_ARCH"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_OS: $RUNNER_OS"     
          echo "-----------------------------------------"
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true  
  
  deploy:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to develop"
        