name: Release version

on:
  workflow_call

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Printing Environment Variables:"
          echo "-----------------------------------------"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED: $GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "RUNNER_ARCH: $RUNNER_ARCH"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_OS: $RUNNER_OS"
          latest_release=${{ github.event.repository.tags_url }}
          echo "Latest Release: $latest_release"
          echo "URL: ${{ github.event.repository.url }}"
          echo "-----------------------------------------"

      - name: Get lastest version
        id: get_lastest_version
        run: |
          latest_release=$(gh release view ${{ github.event.repository.url }} --json tagName -q '.tagName') >> $GITHUB_OUTPUT
          echo "Latest Release: $latest_release"
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true  
          tag: ${{ steps.get_lastest_version.outputs.latest_release }}
          name: ${{ steps.get_lastest_version.outputs.latest_release }}