name: Release version

on:
  workflow_call

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          latest_tag=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/tags" | jq -r 'sort_by(.commit.committer.date) | .[0].name')
          latest_tag=${latest_tag#refs/tags/}
          echo "latest_version=$latest_tag" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true  
          tag: ${{ steps.get_latest_tag.outputs.latest_version }}
          name: ${{ steps.get_latest_tag.outputs.latest_version }}