name: Get Secrets from AWS SecretManager

on:
  workflow_dispatch:

env: 
  RESOURCE_NAME: box-admin-client-kr

jobs:
  get-secret:
    runs-on: ubuntu-22.04
    environment: dev
    permissions:
      id-token: write
      actions: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: ap-northeast-2
        role-session-name: test-deploy
        role-to-assume: ${{ secrets.AWS_ARN }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Get Secrets from AWS SecretManager
      id: get-secret
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: ${{ env.RESOURCE_NAME }}
        parse-json-secrets: true

    - name: unprefix variables
      run: |
        RESOURCE_NAME_UPPERCASE=$(echo $RESOURCE_NAME | tr '[:lower:]' '[:upper:]')
        echo $RESOURCE_NAME_UPPERCASE
        
        for variable in "${!_$RESOURCE_NAME_UPPERCASE_@}"; do 
          echo "${variable#_$RESOURCE_NAME_UPPERCASE_}=${!variable}" >> $GITHUB_ENV
        done

    - name: Show Secrets
      run: |
        echo ${{ steps.get-secret.outputs.secret-ids }}