name: Version Bump

on:
  push:
    branches: [ "main" ]

jobs:
  version-bump:
    name:  'Version Bump'
    runs-on: ubuntu-latest
    permissions:
      contents:  write
    steps:
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
