name: Version Bump

on:
  push:
    branches: [ "main" ]

jobs:
  version-bump:
    name:  'Version Bump'
    runs-on: ubuntu-latest
    permissions:
      contents:  write
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name:  'Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'
          major-wording:  'release'
          minor-wording:  'feature,feat,add,new'
          
      - name: 'Release'
        uses: 'softprops/action-gh-release@v1'
